/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LichLibrary.menu.popup;

import LichLibrary.config.cont;
import LichLibrary.menu.Kategori;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import java.sql.DriverManager;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author eater
 */
public class kPopup extends javax.swing.JFrame {
    cont c = new cont();
    /**
     * Creates new form kPopup
     */
    public kPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        war2 = new javax.swing.JLabel();
        war3 = new javax.swing.JLabel();
        cek = new javax.swing.JCheckBox();
        del = new javax.swing.JToggleButton();
        cl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(241, 200));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        war2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        war2.setForeground(new java.awt.Color(255, 0, 0));
        war2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        war2.setText("Data Yang Bersangkutan");

        war3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        war3.setForeground(new java.awt.Color(255, 0, 0));
        war3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        war3.setText("Akan Dihapus Juga!");

        cek.setText("Ya, Hapus Data Buku");

        del.setBackground(new java.awt.Color(255, 0, 0));
        del.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can.png"))); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        cl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cl.setForeground(new java.awt.Color(255, 0, 0));
        cl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl.setText("X");
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(war2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(war3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(del)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(war2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(war3)
                .addGap(18, 18, 18)
                .addComponent(cek)
                .addGap(18, 18, 18)
                .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        Kategori k = new Kategori();
        
        MongoCollection<Document> col = c.db.getCollection("kategoribuku");
        MongoCollection<Document> col2 = c.db.getCollection("buku");
        MongoCollection<Document> col3 = c.db.getCollection("kategoribuku_relasi");
        MongoCollection<Document> col4 = c.db.getCollection("ulasanbuku");
        MongoCollection<Document> col5 = c.db.getCollection("koleksipribadi");
        Document del = new Document();
        
        if(cek.isSelected()){
            try {
                        c.con = DriverManager.getConnection(c.url);
                        c.stm = c.con.createStatement();
                        String q = "select*from kategori";
                        
                        c.rs=c.stm.executeQuery(q);
                        if (c.rs.next()) {
                            String n = c.rs.getString("kategori");
                            del.put("kategori", n);
                            FindIterable<Document> cv = col2.find(Filters.eq("kategori", n));
                            cv.forEach(val -> {
                                ObjectId id = val.getObjectId("_id");
                                Document d = new Document("_id_buku",id);
                                col4.deleteMany(d);
                                col5.deleteMany(d);
                                col3.deleteMany(d);
                            });
                            col.deleteOne(new Document("NamaKategori",n));
                            col2.deleteMany(del);
                            
                            String de = "delete from kategori where kategori='"+n+"'";
                            c.stm.executeUpdate(de);
                            }else{
                            System.err.println("entek");
                        }
                        this.dispose();
                        c.stm.close();c.con.close();
                    } catch (Exception e) {
                        this.dispose();
                    }
        }
    }//GEN-LAST:event_delActionPerformed

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_clMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cek;
    private javax.swing.JLabel cl;
    private javax.swing.JToggleButton del;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel war2;
    private javax.swing.JLabel war3;
    // End of variables declaration//GEN-END:variables
}
