/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LichLibrary.menu;
import LichLibrary.config.ED;
import LichLibrary.config.cont;
import LichLibrary.config.route;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.DriverManager;
import java.util.Vector;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.bson.Document;
/**
 *
 * @author eater
 */
public class Kategori extends javax.swing.JFrame {
    String point;
    cont c = new cont();
    route r = new route();
    int x = 0;
    String level = "";
    public String g = "";
    /**
     * Creates new form Kategori
     */
    public Kategori() {
        initComponents();
        //to add level
        try {
        c.con = DriverManager.getConnection(c.url);
        c.stm = c.con.createStatement();
        String show = "select * from log";
//      String del = "delete from log where status='login'";
        c.rs = c.stm.executeQuery(show);
        if (c.rs.next()) {                
        level = c.rs.getString("level");
        }               
         c.stm.close();c.con.close();
         } catch (Exception e) {
         e.printStackTrace();
         }
        
        logout.setVisible(false);
        users.setVisible(false);
        denda.setVisible(false);
        line1.setVisible(false);
        line2.setVisible(false);
        Booking.setVisible(false);
        book.setVisible(false);
        pinjam.setVisible(false);
        laporan.setVisible(false);
        kategori.setVisible(false);
        home.setVisible(false);
        staf.setVisible(false);
        
        act.setVisible(false);
        AddPanel.setVisible(false);
        err.setVisible(false);
        
        setTable();
        table_val();
    }
    public void setTable(){
        JTableHeader tableHeader = Gtable.getTableHeader();
        Gtable.setBackground(Color.WHITE);
        tableHeader.setFont(new Font("Segoe UI",Font.BOLD,12));
        tableHeader.setForeground(Color.BLACK);
    }
    public void table_val(){
        MongoCollection<Document> col = c.db.getCollection("kategoribuku");
        MongoCollection<Document> col2 = c.db.getCollection("buku");
        DefaultTableModel dt = (DefaultTableModel) Gtable.getModel();
        dt.setRowCount(0);
        
         FindIterable<Document> show = col.find().sort(new Document("_id",-1));
         show.forEach(val ->{
              Vector v = new Vector();
              v.add(val.getString("NamaKategori"));
              long count = col2.countDocuments(Filters.eq("kategori", val.getString("NamaKategori")));
              if(count!=0){
                  v.add(count);
              }else{
                  v.add("Kosong");
              }
                dt.addRow(v);
         });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        line2 = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        denda = new javax.swing.JLabel();
        book = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        pinjam = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        staf = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Gtable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        act = new javax.swing.JPanel();
        cl = new javax.swing.JLabel();
        del = new javax.swing.JButton();
        AddPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gen = new javax.swing.JTextField();
        Pcl = new javax.swing.JLabel();
        sv = new javax.swing.JButton();
        err = new javax.swing.JLabel();
        reUs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(862, 531));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lich_nav.png")).getImage().getScaledInstance(64, 55, Image.SCALE_DEFAULT)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-48.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        users.setBackground(new java.awt.Color(255, 255, 255));
        users.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        users.setText("Users");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });

        line2.setBackground(new java.awt.Color(0, 153, 255));
        line2.setPreferredSize(new java.awt.Dimension(120, 3));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        line1.setBackground(new java.awt.Color(0, 153, 255));
        line1.setPreferredSize(new java.awt.Dimension(120, 3));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        denda.setBackground(new java.awt.Color(255, 255, 255));
        denda.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        denda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/denda.png"))); // NOI18N
        denda.setText("Denda");
        denda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dendaMouseClicked(evt);
            }
        });

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-book.png"))); // NOI18N
        book.setText("Buku");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
        });

        Booking.setBackground(new java.awt.Color(255, 255, 255));
        Booking.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/booking.png"))); // NOI18N
        Booking.setText("Booking");
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        kategori.setBackground(new java.awt.Color(255, 255, 255));
        kategori.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/genre.png"))); // NOI18N
        kategori.setText("Kategori");
        kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriMouseClicked(evt);
            }
        });

        pinjam.setBackground(new java.awt.Color(255, 255, 255));
        pinjam.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow.png"))); // NOI18N
        pinjam.setText("Peminjaman");
        pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinjamMouseClicked(evt);
            }
        });

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(255, 255, 255));
        laporan.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/writing.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        staf.setBackground(new java.awt.Color(255, 255, 255));
        staf.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        staf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staf.png"))); // NOI18N
        staf.setText("Staf");
        staf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stafMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home)
                            .addComponent(Booking)
                            .addComponent(book)
                            .addComponent(kategori)
                            .addComponent(pinjam)
                            .addComponent(denda)
                            .addComponent(logout)
                            .addComponent(laporan)
                            .addComponent(users)
                            .addComponent(staf))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staf)
                .addGap(12, 12, 12)
                .addComponent(users)
                .addGap(12, 12, 12)
                .addComponent(book)
                .addGap(12, 12, 12)
                .addComponent(kategori)
                .addGap(12, 12, 12)
                .addComponent(Booking)
                .addGap(12, 12, 12)
                .addComponent(pinjam)
                .addGap(12, 12, 12)
                .addComponent(denda)
                .addGap(12, 12, 12)
                .addComponent(laporan)
                .addGap(12, 12, 12)
                .addComponent(logout)
                .addGap(12, 12, 12)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Kategori Buku");

        Gtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kategori", "Jumlah Buku"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Gtable.setFocusable(false);
        Gtable.setGridColor(new java.awt.Color(0, 0, 0));
        Gtable.setOpaque(false);
        Gtable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        Gtable.setShowGrid(true);
        Gtable.setShowVerticalLines(false);
        Gtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Gtable);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        add.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(0, 153, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        add.setText("Add Kategori");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add))
        );

        act.setBackground(new java.awt.Color(255, 255, 255));

        cl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cross.png"))); // NOI18N
        cl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clMouseClicked(evt);
            }
        });

        del.setBackground(new java.awt.Color(255, 0, 0));
        del.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can.png"))); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actLayout = new javax.swing.GroupLayout(act);
        act.setLayout(actLayout);
        actLayout.setHorizontalGroup(
            actLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cl)
                .addContainerGap())
        );
        actLayout.setVerticalGroup(
            actLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(actLayout.createSequentialGroup()
                .addComponent(del)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AddPanel.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Kategori");

        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });

        Pcl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Pcl.setForeground(new java.awt.Color(255, 255, 255));
        Pcl.setText("X");
        Pcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PclMouseClicked(evt);
            }
        });

        sv.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diskette.png"))); // NOI18N
        sv.setText("Submit");
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gen)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pcl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sv)))
                .addContainerGap())
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Pcl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(sv)
                .addContainerGap())
        );

        err.setBackground(new java.awt.Color(255, 255, 255));
        err.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        err.setForeground(new java.awt.Color(255, 51, 51));
        err.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warning.png"))); // NOI18N

        reUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refreshh.png"))); // NOI18N
        reUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reUsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(AddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reUs)
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(reUs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(act, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(err)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        if (x==0) {
            logout.setVisible(true);
            users.setVisible(true);
            denda.setVisible(true);
            line1.setVisible(true);
            line2.setVisible(true);
            Booking.setVisible(true);
            book.setVisible(true);
            pinjam.setVisible(true);
            laporan.setVisible(true);
            kategori.setVisible(true);
            home.setVisible(true);
            if (level.equals("admin")) {
                staf.setVisible(true);
            }
            x=1;
        }else if(x==1){
            home.setVisible(false);
            users.setVisible(false);
            logout.setVisible(false);
            denda.setVisible(false);
            line1.setVisible(false);
            line2.setVisible(false);
            Booking.setVisible(false);
            book.setVisible(false);
            pinjam.setVisible(false);
            laporan.setVisible(false);
            kategori.setVisible(false);
            staf.setVisible(false);
            x=0;
        }
    }//GEN-LAST:event_menuMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        try {
            c.con = DriverManager.getConnection(c.url);
            c.stm = c.con.createStatement();
            String q = "delete from log where username='"+point+"'";
            c.stm.executeUpdate(q);
            r.toLogin();
            this.dispose();
            c.stm.close();c.con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toUsers();
    }//GEN-LAST:event_usersMouseClicked

    private void dendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dendaMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toDenda();
    }//GEN-LAST:event_dendaMouseClicked

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toBook();
    }//GEN-LAST:event_bookMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toBoking();
    }//GEN-LAST:event_BookingMouseClicked

    private void kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toKategori();
    }//GEN-LAST:event_kategoriMouseClicked

    private void pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinjamMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toPinjam();
    }//GEN-LAST:event_pinjamMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toHome();
    }//GEN-LAST:event_homeMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toLaporan();
    }//GEN-LAST:event_laporanMouseClicked

    private void stafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafMouseClicked
        // TODO add your handling code here:
        //        this.dispose();r.toStaf();
    }//GEN-LAST:event_stafMouseClicked

    private void GtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GtableMouseClicked
        // TODO add your handling code here:
        int[] td = Gtable.getSelectedRows();
        int n = 0;
        for(int dt : td){
            n = 10*n+dt;
        }
        act.setVisible(true);
        g=Gtable.getValueAt(n, 0).toString();
    }//GEN-LAST:event_GtableMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        AddPanel.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void clMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clMouseClicked
        // TODO add your handling code here:
        act.setVisible(false);
    }//GEN-LAST:event_clMouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        MongoCollection<Document> col = c.db.getCollection("kategoribuku");
        MongoCollection<Document> col2 = c.db.getCollection("buku");
        Document del = new Document();
        del.put("NamaKategori", g);
        long cek = col2.countDocuments(Filters.eq("kategori", g));
        if(cek!=0){
            try {
                c.con = DriverManager.getConnection(c.url);
                c.stm = c.con.createStatement();
                String q = "insert into kategori(kategori) values ('"+g+"')";
                c.stm.executeUpdate(q);
                r.toKpop();
                c.stm.close();c.con.close();
            } catch (Exception e) {
                err.setText("Error Delete Data!");
                err.setVisible(true);
                //delay showoff
                ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
                executorService.schedule(() -> {
                    err.setVisible(false);
                }, 5, TimeUnit.SECONDS);
            }
        }else{
            col.deleteOne(del);
        }
        table_val();
        act.setVisible(false);
    }//GEN-LAST:event_delActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void PclMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PclMouseClicked
        // TODO add your handling code here:
        AddPanel.setVisible(false);
    }//GEN-LAST:event_PclMouseClicked

    private void reUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reUsMouseClicked
        // TODO add your handling code here:
        table_val();
        act.setVisible(false);
        AddPanel.setVisible(false);
    }//GEN-LAST:event_reUsMouseClicked

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        MongoCollection<Document> col = c.db.getCollection("kategoribuku");
        Document in = new Document();
        if(gen.getText().equals("")){
            err.setText("Colomn Kategori Empty!");
            err.setVisible(true);
            //delay showoff
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                err.setVisible(false);
            }, 5, TimeUnit.SECONDS);
        }else{
            in.put("NamaKategori", gen.getText());

            try {
                col.insertOne(in);
                gen.setText("");
                err.setText("Success Insert Data!");
                err.setForeground(Color.GREEN);
                err.setIcon(new ImageIcon(getClass().getResource("/icon/check.png")));
                err.setVisible(true);
                //delay showoff
                ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
                executorService.schedule(() -> {
                    err.setVisible(false);
                    err.setForeground(Color.red);
                    err.setIcon(new ImageIcon(getClass().getResource("/icon/warning.png")));
                }, 5, TimeUnit.SECONDS);
                table_val();
            } catch (Exception e) {
                err.setText("Error Insert Data!");
                err.setVisible(true);
                //delay showoff
                ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
                executorService.schedule(() -> {
                    err.setVisible(false);
                }, 5, TimeUnit.SECONDS);
            }}
            act.setVisible(false);
    }//GEN-LAST:event_svActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel Booking;
    private javax.swing.JTable Gtable;
    private javax.swing.JLabel Pcl;
    private javax.swing.JPanel act;
    private javax.swing.JButton add;
    private javax.swing.JLabel book;
    private javax.swing.JLabel cl;
    private javax.swing.JButton del;
    private javax.swing.JLabel denda;
    private javax.swing.JLabel err;
    private javax.swing.JTextField gen;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel laporan;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel pinjam;
    private javax.swing.JLabel reUs;
    private javax.swing.JLabel staf;
    private javax.swing.JButton sv;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
