/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LichLibrary.menu;

import LichLibrary.config.ED;
import LichLibrary.config.cont;
import LichLibrary.config.route;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.DriverManager;
import java.util.Calendar;
import java.util.Vector;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.bson.Document;

/**
 *
 * @author eater
 */
public class Users extends javax.swing.JFrame {
    String point;
    cont c = new cont();
    route r = new route();
    int x = 0;
    String level = "";
    String Us = "";
    String Reg = "";
    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        //to add level
        try {
        c.con = DriverManager.getConnection(c.url);
        c.stm = c.con.createStatement();
        String show = "select * from log";
//      String del = "delete from log where status='login'";
        c.rs = c.stm.executeQuery(show);
        if (c.rs.next()) {                
        level = c.rs.getString("level");
        }               
         c.stm.close();c.con.close();
         } catch (Exception e) {
         e.printStackTrace();
         }
        
        logout.setVisible(false);
        users.setVisible(false);
        denda.setVisible(false);
        line1.setVisible(false);
        line2.setVisible(false);
        Booking.setVisible(false);
        book.setVisible(false);
        pinjam.setVisible(false);
        laporan.setVisible(false);
        kategori.setVisible(false);
        home.setVisible(false);
        staf.setVisible(false);
        
        pReg.setVisible(false);
        pUs.setVisible(false);
        clUs.setVisible(false);
        clReg.setVisible(false);
        
        errUs.setVisible(false);
        errReg.setVisible(false);
        
        setTable();
        tableUs();
        tableReg();
        
    }
    public void setTable(){
        JTableHeader tableHeader = tableUs.getTableHeader();
        tableUs.setBackground(Color.WHITE);
        tableHeader.setFont(new Font("Segoe UI",Font.BOLD,12));
        tableHeader.setForeground(Color.BLACK);
        
        JTableHeader tableHeader2 = tableReg.getTableHeader();
        tableReg.setBackground(Color.WHITE);
        tableHeader2.setFont(new Font("Segoe UI",Font.BOLD,12));
        tableHeader2.setForeground(Color.BLACK);
    }
    public void tableUs(){
        MongoCollection<Document> col = c.db.getCollection("user");
        DefaultTableModel dt = (DefaultTableModel) tableUs.getModel();
        dt.setRowCount(0);
        
        FindIterable<Document> show = col.find(Filters.eq("level","user")).sort(new Document("_id",-1));
         show.forEach(val ->{
              Vector v = new Vector();
                v.add(val.getString("username"));
                v.add(val.getString("NamaLengkap"));
                v.add(val.getString("email"));
                v.add(val.getString("Alamat"));
                
                dt.addRow(v);
         });
    }
    public void tableReg(){
        MongoCollection<Document> col = c.db.getCollection("user");
        DefaultTableModel dt = (DefaultTableModel) tableReg.getModel();
        dt.setRowCount(0);
        
        FindIterable<Document> show = col.find(Filters.eq("level", "regist")).sort(new Document("_id",-1));
         show.forEach(val ->{
              Vector v = new Vector();
                v.add(val.getString("username"));
                v.add(val.getString("NamaLengkap"));
                v.add(val.getString("email"));
                v.add(val.getString("Alamat"));
                
                dt.addRow(v);
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pUs = new javax.swing.JPanel();
        delUs = new javax.swing.JButton();
        errUs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reUs = new javax.swing.JLabel();
        clUs = new javax.swing.JLabel();
        pReg = new javax.swing.JPanel();
        acReg = new javax.swing.JButton();
        delReg = new javax.swing.JButton();
        errReg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reReg = new javax.swing.JLabel();
        clReg = new javax.swing.JLabel();
        tabbed = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReg = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        line2 = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        denda = new javax.swing.JLabel();
        book = new javax.swing.JLabel();
        Booking = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        pinjam = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        staf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(862, 531));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lich_nav.png")).getImage().getScaledInstance(64, 55, Image.SCALE_DEFAULT)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pUs.setBackground(new java.awt.Color(255, 255, 255));

        delUs.setBackground(new java.awt.Color(255, 0, 0));
        delUs.setForeground(new java.awt.Color(255, 255, 255));
        delUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can.png"))); // NOI18N
        delUs.setText("Delete");
        delUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUsActionPerformed(evt);
            }
        });

        errUs.setBackground(new java.awt.Color(255, 255, 255));
        errUs.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        errUs.setForeground(new java.awt.Color(255, 51, 51));
        errUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warning.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Users");

        reUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refreshh.png"))); // NOI18N
        reUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reUsMouseClicked(evt);
            }
        });

        clUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cross.png"))); // NOI18N
        clUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clUsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pUsLayout = new javax.swing.GroupLayout(pUs);
        pUs.setLayout(pUsLayout);
        pUsLayout.setHorizontalGroup(
            pUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delUs)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(reUs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clUs)
                .addGap(4, 4, 4))
            .addComponent(errUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pUsLayout.setVerticalGroup(
            pUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUsLayout.createSequentialGroup()
                .addComponent(errUs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(pUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reUs)
                        .addComponent(clUs)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(delUs)
                .addContainerGap())
        );

        pReg.setBackground(new java.awt.Color(255, 255, 255));

        acReg.setBackground(new java.awt.Color(0, 204, 0));
        acReg.setForeground(new java.awt.Color(255, 255, 255));
        acReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-list.png"))); // NOI18N
        acReg.setText("Accept");
        acReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acRegActionPerformed(evt);
            }
        });

        delReg.setBackground(new java.awt.Color(255, 0, 0));
        delReg.setForeground(new java.awt.Color(255, 255, 255));
        delReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-can.png"))); // NOI18N
        delReg.setText("Reject");
        delReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRegActionPerformed(evt);
            }
        });

        errReg.setBackground(new java.awt.Color(255, 255, 255));
        errReg.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        errReg.setForeground(new java.awt.Color(255, 51, 51));
        errReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warning.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Register");

        reReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refreshh.png"))); // NOI18N
        reReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reRegMouseClicked(evt);
            }
        });

        clReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cross.png"))); // NOI18N
        clReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clRegMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pRegLayout = new javax.swing.GroupLayout(pReg);
        pReg.setLayout(pRegLayout);
        pRegLayout.setHorizontalGroup(
            pRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegLayout.createSequentialGroup()
                .addGroup(pRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pRegLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(reReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clReg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRegLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acReg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delReg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        pRegLayout.setVerticalGroup(
            pRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegLayout.createSequentialGroup()
                .addComponent(errReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clReg)
                    .addComponent(reReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(acReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delReg)
                .addContainerGap())
        );

        tabbed.setBackground(new java.awt.Color(255, 255, 255));

        tableReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Name", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReg.setFocusable(false);
        tableReg.setGridColor(new java.awt.Color(0, 0, 0));
        tableReg.setOpaque(false);
        tableReg.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tableReg.setShowGrid(false);
        tableReg.setShowHorizontalLines(true);
        tableReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRegMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableReg);

        tabbed.addTab("Register", jScrollPane2);

        tableUs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Name", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUs.setFocusable(false);
        tableUs.setGridColor(new java.awt.Color(0, 0, 0));
        tableUs.setOpaque(false);
        tableUs.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tableUs.setShowGrid(false);
        tableUs.setShowHorizontalLines(true);
        tableUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableUs);

        tabbed.addTab("Users", jScrollPane3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pReg, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(tabbed)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-48.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        users.setBackground(new java.awt.Color(255, 255, 255));
        users.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        users.setText("Users");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });

        line2.setBackground(new java.awt.Color(0, 153, 255));
        line2.setPreferredSize(new java.awt.Dimension(120, 3));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        line1.setBackground(new java.awt.Color(0, 153, 255));
        line1.setPreferredSize(new java.awt.Dimension(120, 3));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        denda.setBackground(new java.awt.Color(255, 255, 255));
        denda.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        denda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/denda.png"))); // NOI18N
        denda.setText("Denda");
        denda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dendaMouseClicked(evt);
            }
        });

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-book.png"))); // NOI18N
        book.setText("Buku");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
        });

        Booking.setBackground(new java.awt.Color(255, 255, 255));
        Booking.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/booking.png"))); // NOI18N
        Booking.setText("Booking");
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        kategori.setBackground(new java.awt.Color(255, 255, 255));
        kategori.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/genre.png"))); // NOI18N
        kategori.setText("Kategori");
        kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriMouseClicked(evt);
            }
        });

        pinjam.setBackground(new java.awt.Color(255, 255, 255));
        pinjam.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow.png"))); // NOI18N
        pinjam.setText("Peminjaman");
        pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinjamMouseClicked(evt);
            }
        });

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(255, 255, 255));
        laporan.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/writing.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        staf.setBackground(new java.awt.Color(255, 255, 255));
        staf.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        staf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staf.png"))); // NOI18N
        staf.setText("Staf");
        staf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stafMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu)
                    .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home)
                            .addComponent(Booking)
                            .addComponent(book)
                            .addComponent(kategori)
                            .addComponent(pinjam)
                            .addComponent(denda)
                            .addComponent(logout)
                            .addComponent(laporan)
                            .addComponent(users)
                            .addComponent(staf))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staf)
                .addGap(12, 12, 12)
                .addComponent(users)
                .addGap(12, 12, 12)
                .addComponent(book)
                .addGap(12, 12, 12)
                .addComponent(kategori)
                .addGap(12, 12, 12)
                .addComponent(Booking)
                .addGap(12, 12, 12)
                .addComponent(pinjam)
                .addGap(12, 12, 12)
                .addComponent(denda)
                .addGap(12, 12, 12)
                .addComponent(laporan)
                .addGap(12, 12, 12)
                .addComponent(logout)
                .addGap(12, 12, 12)
                .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUsActionPerformed
        // TODO add your handling code here:
        MongoCollection<Document> col = c.db.getCollection("user");
        try {
            col.deleteOne(Filters.eq("username", Us));

            errUs.setText("Delete Success!");
            errUs.setForeground(Color.GREEN);
            errUs.setIcon(new ImageIcon(getClass().getResource("/icon/check.png")));
            errUs.setVisible(true);
            //delay showoff
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errUs.setVisible(false);
                pUs.setVisible(false);
                clUs.setVisible(false);
                errUs.setForeground(Color.red);
                errUs.setIcon(new ImageIcon(getClass().getResource("/icon/warning.png")));
            }, 5, TimeUnit.SECONDS);
            tableUs();
        } catch (Exception e) {
            errUs.setText("Delete Failed!");
            errUs.setVisible(true);
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errUs.setVisible(false);
            }, 5, TimeUnit.SECONDS);
        }
    }//GEN-LAST:event_delUsActionPerformed

    private void reUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reUsMouseClicked
        // TODO add your handling code here:
        tableUs();
        pUs.setVisible(false);
    }//GEN-LAST:event_reUsMouseClicked

    private void clUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clUsMouseClicked
        // TODO add your handling code here:
        pUs.setVisible(false);
        clUs.setVisible(false);
    }//GEN-LAST:event_clUsMouseClicked

    private void acRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acRegActionPerformed
        // TODO add your handling code here:
        MongoCollection<Document> colU = c.db.getCollection("user");
        try {
            colU.updateOne(Filters.eq("username", Reg), Updates.set("level", "user"));
            tableReg();tableUs();
            errReg.setText("Accept Success!");
            errReg.setForeground(Color.GREEN);
            errReg.setIcon(new ImageIcon(getClass().getResource("/icon/check.png")));
            errReg.setVisible(true);
            //delay showoff
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errReg.setVisible(false);
                pReg.setVisible(false);
                clReg.setVisible(false);
                errReg.setForeground(Color.red);
                errReg.setIcon(new ImageIcon(getClass().getResource("/icon/warning.png")));
            }, 5, TimeUnit.SECONDS);
        } catch (Exception e) {
            errReg.setText("Accept Failed!");
            errReg.setVisible(true);
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errReg.setVisible(false);
            }, 5, TimeUnit.SECONDS);
        }

    }//GEN-LAST:event_acRegActionPerformed

    private void delRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRegActionPerformed
        // TODO add your handling code here:
        MongoCollection<Document> col = c.db.getCollection("user");
        try {
            col.deleteOne(Filters.eq("username", Reg));

            errReg.setText("Delete Success!");
            errReg.setForeground(Color.GREEN);
            errReg.setIcon(new ImageIcon(getClass().getResource("/icon/check.png")));
            errReg.setVisible(true);
            //delay showoff
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errReg.setVisible(false);
                pReg.setVisible(false);
                clReg.setVisible(false);
                errReg.setForeground(Color.red);
                errReg.setIcon(new ImageIcon(getClass().getResource("/icon/warning.png")));
            }, 5, TimeUnit.SECONDS);
            tableReg();
        } catch (Exception e) {
            errReg.setText("Delete Failed!");
            errReg.setVisible(true);
            ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.schedule(() -> {
                errReg.setVisible(false);
            }, 5, TimeUnit.SECONDS);
        }
    }//GEN-LAST:event_delRegActionPerformed

    private void reRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reRegMouseClicked
        // TODO add your handling code here:
        tableReg();
        pReg.setVisible(false);
    }//GEN-LAST:event_reRegMouseClicked

    private void clRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clRegMouseClicked
        // TODO add your handling code here:
        pReg.setVisible(false);
        clReg.setVisible(false);
    }//GEN-LAST:event_clRegMouseClicked

    private void tableRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRegMouseClicked
        // TODO add your handling code here:
        int[] td = tableReg.getSelectedRows();
        int n = 0;
        for(int dt : td){
            n = 10*n+dt;
        }
        Reg=tableReg.getValueAt(n, 0).toString();
        clReg.setVisible(true);
        pReg.setVisible(true);
    }//GEN-LAST:event_tableRegMouseClicked

    private void tableUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsMouseClicked
        // TODO add your handling code here:
        int[] td = tableUs.getSelectedRows();
        int n = 0;
        for(int dt : td){
            n = 10*n+dt;
        }
        Us=tableUs.getValueAt(n, 0).toString();
        clUs.setVisible(true);
        pUs.setVisible(true);
    }//GEN-LAST:event_tableUsMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        if (x==0) {
            logout.setVisible(true);
            users.setVisible(true);
            denda.setVisible(true);
            line1.setVisible(true);
            line2.setVisible(true);
            Booking.setVisible(true);
            book.setVisible(true);
            pinjam.setVisible(true);
            laporan.setVisible(true);
            kategori.setVisible(true);
            home.setVisible(true);
            if (level.equals("admin")) {
                staf.setVisible(true);
            }
            x=1;
        }else if(x==1){
            home.setVisible(false);
            users.setVisible(false);
            logout.setVisible(false);
            denda.setVisible(false);
            line1.setVisible(false);
            line2.setVisible(false);
            Booking.setVisible(false);
            book.setVisible(false);
            pinjam.setVisible(false);
            laporan.setVisible(false);
            kategori.setVisible(false);
            staf.setVisible(false);
            x=0;
        }
    }//GEN-LAST:event_menuMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        try {
            c.con = DriverManager.getConnection(c.url);
            c.stm = c.con.createStatement();
            String q = "delete from log where username='"+point+"'";
            c.stm.executeUpdate(q);
            r.toLogin();
            this.dispose();
            c.stm.close();c.con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toUsers();
    }//GEN-LAST:event_usersMouseClicked

    private void dendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dendaMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toDenda();
    }//GEN-LAST:event_dendaMouseClicked

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toBook();
    }//GEN-LAST:event_bookMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toBoking();
    }//GEN-LAST:event_BookingMouseClicked

    private void kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toKategori();
    }//GEN-LAST:event_kategoriMouseClicked

    private void pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinjamMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toPinjam();
    }//GEN-LAST:event_pinjamMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        //        this.dispose();r.toHome();
    }//GEN-LAST:event_homeMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toLaporan();
    }//GEN-LAST:event_laporanMouseClicked

    private void stafMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafMouseClicked
        // TODO add your handling code here:
        this.dispose();r.toStaf();
    }//GEN-LAST:event_stafMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Booking;
    private javax.swing.JButton acReg;
    private javax.swing.JLabel book;
    private javax.swing.JLabel clReg;
    private javax.swing.JLabel clUs;
    private javax.swing.JButton delReg;
    private javax.swing.JButton delUs;
    private javax.swing.JLabel denda;
    private javax.swing.JLabel errReg;
    private javax.swing.JLabel errUs;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel laporan;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel pReg;
    private javax.swing.JPanel pUs;
    private javax.swing.JLabel pinjam;
    private javax.swing.JLabel reReg;
    private javax.swing.JLabel reUs;
    private javax.swing.JLabel staf;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tableReg;
    private javax.swing.JTable tableUs;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
